/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CvRouteImport } from './routes/cv'
import { Route as EmailRouteImport } from './routes/email'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/email': typeof EmailRoute
  '/helpdesk': typeof HelpdeskRoute
  '/interview': typeof InterviewRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/email': typeof EmailRoute
  '/helpdesk': typeof HelpdeskRoute
  '/interview': typeof InterviewRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cv': typeof CvRoute
  '/email': typeof EmailRoute
  '/helpdesk': typeof HelpdeskRoute
  '/interview': typeof InterviewRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cv'
    | '/email'
    | '/helpdesk'
    | '/interview'
    | '/notes'
    | '/planner'
    | '/research'
    | '/api/assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cv'
    | '/email'
    | '/helpdesk'
    | '/interview'
    | '/notes'
    | '/planner'
    | '/research'
    | '/api/assistant'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cv'
    | '/email'
    | '/helpdesk'
    | '/interview'
    | '/notes'
    | '/planner'
    | '/research'
    | '/api/assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CvRoute: typeof CvRoute
  EmailRoute: typeof EmailRoute
  HelpdeskRoute: typeof HelpdeskRoute
  InterviewRoute: typeof InterviewRoute
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRoute
  ResearchRoute: typeof ResearchRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CvRoute: CvRoute,
  EmailRoute: EmailRoute,
  HelpdeskRoute: HelpdeskRoute,
  InterviewRoute: InterviewRoute,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRoute,
  ResearchRoute: ResearchRoute,
  ApiAssistantRoute: ApiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
